// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfweiiycmtylwydferhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmd2VpaXljbXR5bHd5ZGZlcmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjM3ODQsImV4cCI6MjA3MTIzOTc4NH0.B6y3iBDc2FrffoGSl160xiYlZHQ9e3GTMKa6QlBZH60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});